### ISSUE TITLE
При вводе не числа - приложение падает 

### ISSUE THREAD

**Issue by Muxamedin** [potapenkosergey/ser_expereans_py#4]
https://github.com/potapenkosergey/ser_expereans_py/blob/c831835ec20a3c4de19914b7b56a0598c13e0f44/lesson_5/piramida3_9.py#L1

![image](https://user-images.githubusercontent.com/4419752/144666156-bae2cb2f-57eb-46cd-b61b-75e0181ba9a2.png)

![image](https://user-images.githubusercontent.com/4419752/144666037-c687f8ca-517b-4738-8e85-06560ad25823.png)

**Comment by potapenkosergey** [comment]
https://github.com/potapenkosergey/ser_expereans_py.git
Подправил,  lesson_5
<https://github.com/potapenkosergey/ser_expereans_py/tree/main/lesson_5>
,  piramida3_9.py
<https://github.com/potapenkosergey/ser_expereans_py/blob/main/lesson_5/piramida3_9.py>
v_1
<https://github.com/potapenkosergey/ser_expereans_py/commit/9ea7b109ac65a2296db3bbc4f1c7017692518971>

пт, 3 дек. 2021 г. в 22:07, Mikel Bily ***@***.***>:

**Comment by potapenkosergey** [comment]
Вроде выгрузил на репозиторий с исправлением, работало, файл:
piramida3_9.py kommit v_1

сб, 4 дек. 2021 г. в 00:14, Mikel Bily ***@***.***>:
